language: node_js
node_js:
  - "8"
  - "10"
os: linux
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install: yarn
before_script: sh -c "git log | head -12"
script: yarn run coverage
after_success:
  - coveralls < ./coverage/lcov.info
