environment:
  matrix:
    # node.js
    - nodejs_version: "12"
    - nodejs_version: "10"
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn run coverage

build: off

# build version format
version: "{build}"
